import type { Card } from "@/types";
const allCards: Card[] = [
  {
    id: 0,
    name: "カード1",
    description: "カード1の説明",
    company: "会社1",
    waste: 1,
    hungry: 1,
    atk: 1,
  },
  {
    id: 1,
    name: "カード2",
    description: "カード2の説明",
    company: "会社2",
    waste: 2,
    hungry: 2,
    def: 2,
  },
  {
    id: 2,
    name: "カード3",
    description: "カード3の説明",
    company: "会社3",
    waste: 3,
    hungry: 3,
    tech: 3,
  },
  {
    id: 3,
    name: "カード4",
    description: "カード4の説明",
    company: "会社4",
    waste: 4,
    hungry: 4,
    heal: 4,
  },
  {
    id: 4,
    name: "カード5",
    description: "カード5の説明",
    company: "会社5",
    waste: 5,
    hungry: 5,
    priority: 5,
  },
  {
    id: 5,
    name: "カード6",
    description: "カード6の説明",
    company: "会社6",
    waste: 6,
    hungry: 6,
    atk: 6,
  },
  {
    id: 6,
    name: "カード7",
    description: "カード7の説明",
    company: "会社7",
    waste: 7,
    hungry: 7,
    def: 7,
  },
  {
    id: 7,
    name: "カード8",
    description: "カード8の説明",
    company: "会社8",
    waste: 8,
    hungry: 8,
    tech: 8,
  },
  {
    id: 8,
    name: "カード9",
    description: "カード9の説明",
    company: "会社9",
    waste: 9,
    hungry: 9,
    heal: 9,
  },
  {
    id: 9,
    name: "カード10",
    description: "カード10の説明",
    company: "会社10",
    waste: 10,
    hungry: 10,
    priority: 10,
  },
]; //!100枚くらいあるから重くなったら分割する
export default allCards;
